# Generated by Django 3.0.4 on 2020-04-25 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_likes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
